# Generated by Django 5.1.6 on 2025-02-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_has_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='deleted',
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
