# Generated by Django 5.1.6 on 2025-02-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_deleted_customuser_has_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
