# Generated by Django 5.1.6 on 2025-03-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid-pending', 'Paid - Pending Confirmation'), ('processing', 'Processing'), ('out-for-delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='paid-pending', max_length=20),
        ),
    ]
