# Generated by Django 5.1.6 on 2025-03-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='N/A', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid-pending', 'Paid - Pending Confirmation'), ('processing', 'Processing'), ('awaiting-pickup', 'Awaiting Pickup'), ('out-for-delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='paid-pending', max_length=20),
        ),
    ]
